version: '3'

services:
  myapp:
    build:
      context: . #onde vai buscar o arquivo para ser buildado
      dockerfile: Dockerfile #nome do arquivo do tipo dockerfile
    container_name: minha_aplicacao
    restart: always
    ports: 
      - 8080:80
    volumes: 
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:8.2
    container_name: mysql_livia
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports: 
      - 3306:3306
    volumes:
      - ./mysql/:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
      driver: bridge